import { Metadata } from "next"
import { MainComponent } from "./components/MainComponent"

async function getTables() {
	const url = `${process.env.VERCEL_URL}/api/mesas`
	const response = await fetch(url, { next: { revalidate: 10 } })
	return response.json()
}

async function getOrders() {
    const url = `${process.env.VERCEL_URL}/api/pedidos`
    const response = await fetch(url, { next: { revalidate: 10 } })
    return response.json()
}

export const metadata: Metadata = {
    title: "Mesas – Controle de Negócio",
    description: "Generated by create next app",
}

export default async function RestaurantTables() {
    const restaurantTables = await getTables()
    const restaurantOrders = await getOrders()
    
    return <MainComponent restaurantTablesFromAPI={restaurantTables} restaurantOrdersFromAPI={restaurantOrders} />
}
