import { Metadata } from "next"
import { MainComponent } from "./components/MainComponent"

export const metadata: Metadata = {
    title: "Dashboard – Controle de Negócio",
    description: "Generated by create next app",
}

export default function Dashboard() {
    return <MainComponent />
}
