import type { Metadata } from "next"
import "./globals.css"
import { TableContextProvider } from "@/contexts/MainContext"

export const metadata: Metadata = {
	title: "Controle de Negócio",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="pt-BR">
			<body>
				<TableContextProvider>
					{children}
				</TableContextProvider>
			</body>
		</html>
	)
}
